--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Diduhless/Parties
build-by-default: true
projects:
  Parties:
    path: ""
    icon: "icon.png"
    libs:
      - src: GiantQuartz/EasyUI/EasyUI
        version: 1.3.0
...
